hyeonsang010716/ChatBoard

src/view/main_screen.html
=> feat(main-page): test API response

src/model/img_model.py, src/model/kor_to_eng.py
style(img_model): 코드 정리
feat(kor_to_eng): 사용자 input(한국어)을 llm이 이해하기 쉽도록 영어로 번역해주는 함수 추가
=> Feat/llm img upload - add kor_to_eng.py

src/model/kor_to_eng.py, src/model/rag_to_llm.py
=> FIX: 환경변수로드 추가

src/static/css/main_screen.css, src/static/js/main_screen.js
[ 서버 측에서 연결해야 할 사항 ]
현재 버전은 임의로 json을 지정하여 만든 상황입니다.
따라서 서버 측에서 보드게임들에 대한 이름과 플레이 시간, 사진 링크 등이 담긴 json 파일을 해당 파일로 전달해 주는 기능 하나와
페이지에서 어떤 보드게임을 선택해서 POST로 보낸 보드게임의 이름을 확인하고, 요청을 수락하는 등의 기능을 구현하면 주석처리된 코드를 사용할 수 있습니다.
=> FEAT(main-page): 보드게임 선택 화면 및 전달 구현

src/static/css/main_screen.css, src/static/js/main_screen.js, src/view/main_screen.html
여러 홈페이지에서 볼 수 있는 "페이지 맨 위로 올리기 (Scroll-to-Top)" 버튼 및 기능을 추가하였습니다.
=> FEAT(main-page): 일정 아래로 내려가면 맨 위로 보내는 버튼 추가

src/static/css/rule_chat.css, src/static/js/rule_chat.js, src/view/rule_chat.html
현재 채팅 입력 시 질의 응답 받기 전까지 Loading 메시지를 띄우는 것 까지 구현
추가로 해야할 사항
1. 사진 업로드 및 보내기
2. 메인에서 선택 했을 때 해당 내용을 반영 시키기
3. 추후 추가
=> feat:대화기능 추가

src/model/test_llm.py
질문하면 답하는 llm 추가했습니다. 프론트 백 연결을 위한 테스트 파일입니다.
=> TEST: test로 질문하면 답하는 llm 추가

src/model/test_llm.py
=> FIX: key error 환경변수업데이트

src/static/css/rule_chat.css, src/static/js/rule_chat.js, src/view/rule_chat.html
=> feat : 이미지 업로드 하면 채팅 창에 반영

src/static/css/rule_chat.css, src/static/js/rule_chat_anim.js, src/view/rule_chat.html
=> feat : 서브 페이지 CSS 디자인 추가

src/model/Advanced_RAG/generation.py, src/model/Advanced_RAG/query_translation.py, src/model/Advanced_RAG/retrieval.py, src/model/Advanced_RAG/retrival.py, src/model/test.py
비동기 Advanced RAG.
구현된 거:
멀티 쿼리, 검색 문서 정확도순 정렬
구현할 거:
PDF 임베딩
=> FEAT: async advanced RAG

src/model/Advanced_RAG/generation.py
=> FEAT: find_file_path

src/static/css/main_screen.css, src/static/js/main_screen.js, src/static/js/scroll_toggle.js
기존 DOMContentLoaded 내에서만 함수선언을 진행하는 형식에서
DOMContentLoad가 되면 각 버튼들에 대한 이벤트리스너를 할당하는 함수만 실행하게 하고,
각 이벤트리스너 할당 함수 및 각 버튼에 대한 함수는 그 밖에 만들어
유지보수를 쉽게 하였습니다.
=> REFACTOR: 메인 페이지의 js 코드 리팩토링

src/model/Advanced_RAG/generation.py
FEAT: generation.py에 img분석 추가
img_path가 있을 경우만 분석합니다. 없는 경우 No image information
=> FEAT: generation.py에 img분석 추가

src/model/Advanced_RAG/generation.py
=> CHORE: 테스트하려고 수정, 프롬프트 수정

src/static/css/main_screen.css, src/static/js/main_screen.js
이제 검색기준에 맞는 게임이 없을 경우, 게임이 없다고 출력해줍니다.
=> FEAT: 검색한 기준에 맞는 item이 없을 경우 문구 출력

src/static/js/main_screen.js
기존 넘기는 주소에서 게임에 대한 정보를 다 전달하게 하였다면
게임의 이름만 전달하도록 수정하였습니다
=> FIX: 룰 소개 페이지로 넘기는 url을 이름만 넘기게 변경

src/static/js/main_screen.js
기존 공백이 추가되면 검색을 잘 하지 못하는 경우를 수정했습니다.
=> FIX: 검색화면에 공백이 추가되는 case 추가

src/model/Advanced_RAG/generation.py, src/model/Advanced_RAG/img_model.py
img_model 해상도 낮추기
토큰 줄이기 대작전..
=> FEAT: img_model 해상도 낮추기 & 프롬프트 변경

src/control/page.py, src/model/Advanced_RAG/img_model.py
fix : llm에 인원수 전달 기능 수정
인원수가 상관 없을 때는 It doesn't matter how many people it is 로 전달 됩니다.
=> fix : llm에 인원수 전달 기능 수정

src/control/page.py, src/model/Advanced_RAG/generation.py, src/model/Advanced_RAG/retrieval.py, src/model/Advanced_RAG/t_generation.py
fix : 히스토리 llm에 맞춰서 control 수정했습니다.
=> fix : 히스토리 llm에 맞춰서 control 수정했습니다.

src/control/page.py, src/main.py
=> fix : 불필요한 주석 정리

src/model/Advanced_RAG/img_model.py
=> CHORE: 주석 정리

src/static/js/main_screen.js
이제 보드게임에 대한 정보가 없을 때,
문의사항 링크를 직접 클릭하여 구글 폼에 접속할 수 있습니다.
=> STYLE: response 테스트 용 console.log 제거

src/model/Advanced_RAG/img_model.py, src/model/Advanced_RAG/t_generation.py
=> FEAT: 이미지 설명 반환없이 인코딩 바로 넘기기
